name: storeapp
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.6
  #flutter_native_splash: ^2.3.5
  animate_do: ^3.1.2
  persistent_bottom_nav_bar: ^5.0.2
  flutter_staggered_animations: ^1.1.1
  get_storage: ^2.1.1
  image_picker: ^1.0.5
  dartz: ^0.10.1
  #flutter_launcher_icons: ^0.13.1
  flutter_phoenix: ^1.1.1
  flutter_barcode_scanner: ^2.0.0
  dropdown_search: ^5.0.6
  flutter_image_compress: ^2.1.0
  flutter_custom_dialog: ^1.3.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  easy_date_timeline: ^1.0.2
  google_maps_place_picker_mb: ^3.0.2
  pinput: ^3.0.1
  flutter_map: ^4.0.0
  latlng: ^1.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  google_maps_flutter: ^2.5.0
  geocoder2: ^1.4.0
  location: ^5.0.3
  google_places_for_flutter: ^1.0.1
  google_directions_api: ^0.9.1
  dio: ^5.4.0
  google_maps_utils: ^2.0.0+1
  flutter_html: ^3.0.0-beta.2
  flutter_mapbox_navigation: ^0.2.2


 

 


 





 
 

 

 

 
 

 

  

 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/images/splash.png
  color: "#FF3758"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_black.jpg"
  min_sdk_android: 21 
  

flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
   - assets/images/

  fonts:
     - family: Tajawal
       fonts:
         - asset: assets/fonts/Tajawal-Regular.ttf