// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArFIBiMqQEqQp1xysd_XOMP_B8T3iJ3z4',
    appId: '1:451670836661:web:0364474199b7512f4305fc',
    messagingSenderId: '451670836661',
    projectId: 'storeapp-8cc25',
    authDomain: 'storeapp-8cc25.firebaseapp.com',
    storageBucket: 'storeapp-8cc25.appspot.com',
    measurementId: 'G-K53E8TYYVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwH9zs98BM5dB1Eno6hJB0YQD36DVBRvA',
    appId: '1:451670836661:android:90d87d6929ddecf94305fc',
    messagingSenderId: '451670836661',
    projectId: 'storeapp-8cc25',
    storageBucket: 'storeapp-8cc25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYeUfWHXVx7pU9nAbmmglGF2h5liUNsPo',
    appId: '1:451670836661:ios:6973a9614821b6e24305fc',
    messagingSenderId: '451670836661',
    projectId: 'storeapp-8cc25',
    storageBucket: 'storeapp-8cc25.appspot.com',
    iosBundleId: 'com.darko.storeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYeUfWHXVx7pU9nAbmmglGF2h5liUNsPo',
    appId: '1:451670836661:ios:da045414d66a83d34305fc',
    messagingSenderId: '451670836661',
    projectId: 'storeapp-8cc25',
    storageBucket: 'storeapp-8cc25.appspot.com',
    iosBundleId: 'com.darko.storeapp.RunnerTests',
  );
}
